version: "4.9"
networks:
  fullstack:
    driver: bridge

services:
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks:
      - fullstack
  postgres:
    networks:
      - fullstack
    image: postgres:14-alpine
    ports:
      - '5432'
    volumes:
      - postgres_db:/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=localhost

  app:
    networks:
      - fullstack
    container_name: go-notifications
    image: go-notifications:latest
    restart: unless-stopped
    ports:
      - '8741:8741'
    volumes:
      - api:/usr/src/app/
    depends_on:
      - nats
volumes:
  api:
  postgres_db:
